"""Check committed files and the Python writer's exact serialization.

Each golden has a parsed JSON header sidecar. Tests compare generated bytes
with committed files and check format constants against literal values.

Regenerate with ``python tests/generate_goldens.py`` only when intentionally
updating fixtures or serialization, and review both binary and sidecar diffs.
A serialization change does not necessarily change the format.
"""

import io
import json
import pathlib
import struct

import numpy as np
import pytest

import cmb_format as cmb
from cases import CASES, build_bytes

GOLDENS = pathlib.Path(__file__).parent / "goldens"
CASE_NAMES = sorted(CASES)


@pytest.mark.parametrize("name", CASE_NAMES)
def test_golden_serialization_sidecars_and_arrays_are_unchanged(name):
    expected = (GOLDENS / f"{name}.cmb").read_bytes()
    assert build_bytes(CASES[name]) == expected

    with io.BytesIO(expected) as f:
        header, data_start = cmb.read_header(f)
        # Keep the readable sidecar consistent with its binary fixture.
        assert header == json.loads((GOLDENS / f"{name}.header.json").read_text())
        if "arrays" in header["mesh"]:
            cmb.read_arrays(f, data_start, header["mesh"]["arrays"])
        if "base_mesh" in header["mesh"]:
            cmb.read_arrays(f, data_start, header["mesh"]["base_mesh"]["arrays"])
        for model in header["models"].values():
            # Reading also verifies the stored SHA-256 checksum.
            cmb.read_array(f, data_start, model["array"])
        n_cells = _cell_count(f, header, data_start)
        wrong = {
            model_name: entry["array"]["shape"][0]
            for model_name, entry in header["models"].items()
            if entry["array"]["shape"] != [n_cells]
        }
    assert wrong == {}, f"{name} has {n_cells} cells but models {wrong}"


def test_magic_is_literal_and_trailer_uses_byte_eight_offsets():
    raw = (GOLDENS / "tensor_with_models.cmb").read_bytes()
    assert raw[:8] == b"CELLMODB"
    assert raw[-8:] == b"CELLMODB"
    (declared,) = struct.unpack("<Q", raw[-16:-8])
    header_start = len(raw) - 16 - declared
    assert json.loads(raw[header_start:-16].decode("utf-8"))["format_version"] == 1
    # Use the format's literal offset independently of the MAGIC constant.
    _, data_start = cmb.read_header(io.BytesIO(raw))
    assert data_start == 8


def test_dtype_tokens_are_exactly_the_documented_set():
    # Literal tokens catch renames that a shared writer/reader table would hide.
    expected = {
        "float64",
        "float32",
        "int64",
        "int32",
        "int16",
        "int8",
    }
    assert set(cmb.DTYPE_TO_NUMPY) == expected
    header = json.loads((GOLDENS / "all_dtypes.header.json").read_text())
    assert {m["array"]["dtype"] for m in header["models"].values()} == expected


def test_header_key_names_are_stable():
    header = json.loads(
        (GOLDENS / "octree_base_padding_models.header.json").read_text()
    )
    assert set(header) == {"format_version", "mesh", "metadata", "models"}
    assert set(header["mesh"]) == {"arrays", "base_mesh", "mesh_class", "mode"}
    assert set(header["mesh"]["base_mesh"]) == {
        "arrays",
        "default_padding",
        "mesh_class",
    }
    assert set(header["mesh"]["arrays"]["level"]) == {
        "checksum",
        "dtype",
        "length",
        "offset",
        "shape",
    }
    assert header["mesh"]["arrays"]["level"]["checksum"].startswith("sha256:")


def test_reference_mode_carries_no_mesh_class():
    # The minimal reference descriptor identifies the mode and cell count.
    header = json.loads((GOLDENS / "reference_models_only.header.json").read_text())
    assert header["mesh"]["mode"] == "reference"
    assert "mesh_class" not in header["mesh"]
    assert header["mesh"]["n_cells"] == 3


def test_every_case_has_both_a_golden_and_a_sidecar():
    # Keep fixture definitions and committed files in sync.
    for name in CASE_NAMES:
        assert (GOLDENS / f"{name}.cmb").is_file(), f"missing golden for {name}"
        assert (GOLDENS / f"{name}.header.json").is_file(), (
            f"missing sidecar for {name}"
        )
    stray = {p.stem for p in GOLDENS.glob("*.cmb")} - set(CASE_NAMES)
    assert not stray, f"goldens with no case in cases.py: {sorted(stray)}"


def _cell_count(f, header, data_start):
    """Number of cells a golden's mesh descriptor describes."""
    mesh = header["mesh"]
    if mesh.get("mode") == "reference":
        return mesh["n_cells"]
    arrays = mesh["arrays"]
    if mesh["mesh_class"] == "TensorMesh":
        return (
            arrays["h_x"]["shape"][0]
            * arrays["h_y"]["shape"][0]
            * arrays["h_z"]["shape"][0]
        )
    if mesh["mesh_class"] == "UniformTensorMesh":
        return int(np.prod(cmb.read_array(f, data_start, arrays["shape"])))
    if mesh["mesh_class"] == "OctreeMesh":
        return arrays["level"]["shape"][0]
    raise AssertionError(f"unhandled mesh_class {mesh['mesh_class']!r}")
